version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: bookinguser
      POSTGRES_PASSWORD: bookingpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - booking-network

  backend:
    build: ./backend
    container_name: booking-backend
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/bookingdb
      - SPRING_DATASOURCE_USERNAME=bookinguser
      - SPRING_DATASOURCE_PASSWORD=bookingpassword
    depends_on:
      - postgres-db
    networks:
      - booking-network

  frontend:
    build: ./frontend
    container_name: booking-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - booking-network

volumes:
  pgdata:

networks:
  booking-network:
    driver: bridge